services:
  - type: web
    name: auto-ani-website
    env: node
    plan: starter
    region: frankfurt  # Closest to Kosovo for optimal latency
    branch: main

    # Optimized build and start commands
    buildCommand: npm install
    startCommand: node server.js

    # Health check endpoint
    healthCheckPath: /

    # Environment variables
    envVars:
      - key: NODE_ENV
        value: production
        key: PORT
        value: 10000

    # Auto-deployment
    autoDeploy: true

