services:
  - type: web
    name: auto-ani-website
    env: node
    plan: starter
    region: frankfurt  # Closest to Kosovo for optimal latency
    branch: main

    # Optimized build and start commands
    buildCommand: |
      npm ci --only=production &&
      NODE_OPTIONS='--max-old-space-size=1024' npm run build &&
      rm -rf .next/cache
    startCommand: npm start

    # Health check endpoint
    healthCheckPath: /

    # Environment variables
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SITE_URL
        value: https

    # Auto-deployment
    autoDeploy: true

