services:
  - type: web
    name: auto-ani-website
    env: node
    plan: starter
    region: frankfurt  # Closest to Kosovo for optimal latency
    branch: main

    # Optimized build and start commands
    buildCommand: |
      npm ci --only=production &&
      NODE_OPTIONS='--max-old-space-size=1024' npm run build &&
      rm -rf .next/cache
    startCommand: npm start

    # Health check endpoint
    healthCheckPath: /

    # Environment variables
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SITE_URL
        value: https://auto-ani-website.onrender.com

      # Shared Sanity CMS Configuration
      - key: NEXT_PUBLIC_SANITY_PROJECT_ID
        value: j2t31xge
      - key: NEXT_PUBLIC_SANITY_DATASET
        value: production
      - key: SANITY_API_TOKEN
        value: skVALaMvvJIxP9krYTpB6SYM6XgH3fe60cDRTpVg05znY5DlDGIx1LvUMre94xah8O1bk6ZIiz5QwNz7aA6B5XisFj8mWid17JAgnWh5tuncOehX5gsYt2oNpVxfpS9xsa1YWxHCjMUxkwGeeH9bynKZGz5OQFwIeNARmmN3ajJCCEfgMUiO

      # Performance optimizations
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: NODE_OPTIONS
        value: "--max-old-space-size=512"
      - key: UV_THREADPOOL_SIZE
        value: "2"

      # Contact form configuration (if needed)
      - key: CONTACT_EMAIL
        value: contact@autosalonani.com

    # Auto-deployment
    autoDeploy: true

    # Custom headers for optimization
    headers:
      - path: "/_next/static/*"
        headers:
          - key: "Cache-Control"
            value: "public, max-age=31536000, immutable"
      - path: "/images/*"
        headers:
          - key: "Cache-Control"
            value: "public, max-age=604800"
      - path: "/api/*"
        headers:
          - key: "Cache-Control"
            value: "no-store, must-revalidate"
